// Generated by ChatGPT - reviewed by Alejandro Armario - 08/04/2026
// Importamos express (asumiendo que ya tienes la app creada)
const express = require('express');
const router = express.Router();

/**
 * Datos mock de equipos por grupo (A-H)
 * Cada grupo contiene un array de equipos con estadísticas básicas
 */
const championsLeagueData = {
  A: [
    { name: 'Bayern Munich', country: 'Germany', points: 12, won: 4, drawn: 0, lost: 0 },
    { name: 'Manchester United', country: 'England', points: 9, won: 3, drawn: 0, lost: 1 }
  ],
  B: [
    { name: 'Real Madrid', country: 'Spain', points: 10, won: 3, drawn: 1, lost: 0 },
    { name: 'Napoli', country: 'Italy', points: 7, won: 2, drawn: 1, lost: 1 }
  ],
  C: [
    { name: 'PSG', country: 'France', points: 8, won: 2, drawn: 2, lost: 0 }
  ],
  D: [
    { name: 'Inter Milan', country: 'Italy', points: 6, won: 2, drawn: 0, lost: 2 }
  ],
  E: [],
  F: [],
  G: [],
  H: []
};

/**
 * GET /champions-league/teams/:groupId
 * Devuelve los equipos de un grupo específico (A-H)
 */
router.get('/champions-league/teams/:groupId', async (req, res) => {
  try {
    // Obtenemos el parámetro groupId de la URL
    const { groupId } = req.params;

    // Validación: verificar que groupId exista
    if (!groupId) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'groupId es requerido'
      });
    }

    // Normalizamos el valor a mayúsculas (por si viene en minúsculas)
    const normalizedGroupId = groupId.toUpperCase();

    // Lista de grupos válidos
    const validGroups = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];

    // Validación: comprobar que el grupo esté dentro de A-H
    if (!validGroups.includes(normalizedGroupId)) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'groupId inválido. Debe ser un valor entre A-H'
      });
    }

    // Obtenemos los equipos del grupo solicitado
    const teams = championsLeagueData[normalizedGroupId];

    // Respondemos con éxito y los datos
    return res.status(200).json({
      success: true,
      data: teams,
      error: null
    });

  } catch (error) {
    // Manejo de errores inesperados
    return res.status(500).json({
      success: false,
      data: null,
      error: 'Error interno del servidor'
    });
  }
});

// Exportamos el router para usarlo en la app principal
module.exports = router;